variables:
  GIT_SUBMODULE_STRATEGY: recursive
  ORD_SOUMET_SHELL: /bin/bash

before_script:
  - export ORDENV_SITE_PROFILE=20210129
  - export ORDENV_COMM_PROFILE=eccc/20210309
  - export ORDENV_GROUP_PROFILE=eccc/cmc/1.9.5
  - . /fs/ssm/main/env/ordenv-boot-20201118.sh

  - export EC_ATOMIC_PROFILE_VERSION=1.13.0

  # - export CLICOLOR_FORCE=1

stages:
  - configure
  - build
  - test_batch

# configure_job_regular_intel:
#   stage: configure
#   variables:
#     build_dir: /home/vma000/ci-builds/io-server/${CI_PROJECT_PATH}/${CI_BUILD_REF_NAME}/${CI_PIPELINE_ID}/${REGULAR_MACHINE_1}
#   script:
#     - source /home/vma000/space_ords/ci-admin-bundle/environments/eccc-setup-intel.sh
#     - mkdir -pv ${build_dir}
#     - cd ${build_dir}
#     - cmake ${CI_PROJECT_DIR}

# build_job_regular_intel:
#   stage: build
#   variables:
#     build_dir: /home/vma000/ci-builds/io-server/${CI_PROJECT_PATH}/${CI_BUILD_REF_NAME}/${CI_PIPELINE_ID}/${REGULAR_MACHINE_1}
#   script:
#     - source /home/vma000/space_ords/ci-admin-bundle/environments/eccc-setup-intel.sh
#     - cd ${build_dir}
#     - make

# test_job_regular_intel_single_node:
#   stage: test_batch
#   variables:
#     build_dir: /home/vma000/ci-builds/io-server/${CI_PROJECT_PATH}/${CI_BUILD_REF_NAME}/${CI_PIPELINE_ID}/${REGULAR_MACHINE_1}
#     NUM_CPUS: "40"
#     ORD_SOUMET_MACH: ${REGULAR_MACHINE_1}
#     ORD_SOUMET_C: "${NUM_CPUS}"
#     ORD_SOUMET_W: "30"
#     ORD_SOUMET_JN: io-server-regular-single-node
#   script:
#     - cd ${build_dir}
#     - ${build_dir}/tests/io_server_circular_buffer_single_thread
#     - ${build_dir}/tests/io_server_cb_unaligned_input
#     - mpirun -n 4           ${build_dir}/tests/io_server_circular_buffer
#     - mpirun -n 4           ${build_dir}/tests/io_server_circular_buffer_fill
#     - mpirun -n ${NUM_CPUS} ${build_dir}/tests/io_server_distributed_circular_buffer
#     - mpirun -n 4           ${build_dir}/tests/io_server_test_memory_arena
#     - mpirun -n 16          ${build_dir}/tests/io_server_cb_plus_dcb                 1 2 2 4 0
#     - mpirun -n 3           ${build_dir}/tests/io_server_dcb_edge_case_1
#     - mpirun -n 3           ${build_dir}/tests/io_server_dcb_unaligned_input
#     # - mpirun -n ${NUM_CPUS} ${build_dir}/tests/io_server_model_write                 1 2 2

# test_job_regular_intel_multi_node:
#   stage: test_batch
#   variables:
#     build_dir: /home/vma000/ci-builds/io-server/${CI_PROJECT_PATH}/${CI_BUILD_REF_NAME}/${CI_PIPELINE_ID}/${REGULAR_MACHINE_1}
#     NUM_CPUS: "80"
#     ORD_SOUMET_MACH: ${REGULAR_MACHINE_1}
#     ORD_SOUMET_C: "${NUM_CPUS}x1"
#     ORD_SOUMET_W: "30"
#     ORD_SOUMET_JN: io-server-regular-multi-node
#   script:
#     - cd ${build_dir}
#     - mpirun -n ${NUM_CPUS} ${build_dir}/tests/io_server_model_write 1 10 6

configure_job_big_intel:
  stage: configure
  variables:
    build_dir: /home/vma000/ci-builds/io-server/${CI_PROJECT_PATH}/${CI_BUILD_REF_NAME}/${CI_PIPELINE_ID}/big/intel
  tags:
    - login_node
  script:
    - . ssmuse-sh -d main/opt/cmake/cmake-3.16.4
    - mkdir -pv ${build_dir}
    - cd ${build_dir}
    - pwd
    - cmake ${CI_PROJECT_DIR}

build_job_big_intel:
  stage: build
  variables:
    build_dir: /home/vma000/ci-builds/io-server/${CI_PROJECT_PATH}/${CI_BUILD_REF_NAME}/${CI_PIPELINE_ID}/big/intel
  tags:
    - login_node
  script:
    - . ssmuse-sh -d main/opt/cmake/cmake-3.16.4
    - cd ${build_dir}
    - pwd
    - make

test_job_big_intel_single_node:
  stage: test_batch
  variables:
    build_dir: /home/vma000/ci-builds/io-server/${CI_PROJECT_PATH}/${CI_BUILD_REF_NAME}/${CI_PIPELINE_ID}/big/intel
    NUM_CPUS: "40"
    ORD_SOUMET_MACH: ${BIG_MACHINE_2}
    ORD_SOUMET_C: "${NUM_CPUS}"
    ORD_SOUMET_W: "30"
    ORD_SOUMET_JN: io-server-big-single-node
  script:
    - cd ${build_dir}
    - pwd
    - ${build_dir}/tests/io_server_circular_buffer_single_thread
    - ${build_dir}/tests/io_server_cb_unaligned_input
    - aprun -n 4           ${build_dir}/tests/io_server_circular_buffer
    - aprun -n 4           ${build_dir}/tests/io_server_circular_buffer_fill
    - aprun -n ${NUM_CPUS} ${build_dir}/tests/io_server_distributed_circular_buffer
    - aprun -n 4           ${build_dir}/tests/io_server_test_memory_arena
    - aprun -n 16          ${build_dir}/tests/io_server_cb_plus_dcb                 1 2 2 4 0
    - aprun -n 3           ${build_dir}/tests/io_server_dcb_edge_case_1
    - aprun -n 3           ${build_dir}/tests/io_server_dcb_unaligned_input
    # - aprun -n ${NUM_CPUS} ${build_dir}/tests/io_server_model_write                 1 2 2

test_job_big_intel_multi_node:
  stage: test_batch
  variables:
    build_dir: /home/vma000/ci-builds/io-server/${CI_PROJECT_PATH}/${CI_BUILD_REF_NAME}/${CI_PIPELINE_ID}/big/intel
    NUM_CPUS: "80"
    ORD_SOUMET_MACH: ${BIG_MACHINE_2}
    ORD_SOUMET_C: "${NUM_CPUS}x1"
    ORD_SOUMET_W: "30"
    ORD_SOUMET_JN: io-server-big-multi-node
  script:
    - cd ${build_dir}
    # - aprun -n ${NUM_CPUS} ${build_dir}/tests/io_server_model_write 1 10 6
