variables:
  GIT_SUBMODULE_STRATEGY: recursive
  ORD_SOUMET_SHELL: /bin/bash

before_script:
  - export ORDENV_SITE_PROFILE=20210129
  - export ORDENV_COMM_PROFILE=eccc/20210309
  - export ORDENV_GROUP_PROFILE=eccc/cmc/1.9.5
  - . /fs/ssm/main/env/ordenv-boot-20201118.sh

  - export EC_ATOMIC_PROFILE_VERSION=1.13.0

  # - export CLICOLOR_FORCE=1

stages:
  - configure
  - build
  - test_batch

configure_job_regular_gnu:
  stage: configure
  variables:
    build_dir: ${RPN_CI_BASE_DIR}/${CI_PROJECT_PATH}/${CI_BUILD_REF_NAME}/${CI_PIPELINE_ID}/${REGULAR_MACHINE_1}
  script:
    - source ${RPN_CI_SCRIPTS}/io-server-setup-gnu-7.4.sh
    - mkdir -pv ${build_dir}
    - cd ${build_dir}
    - cmake ${CI_PROJECT_DIR}

build_job_regular_gnu:
  stage: build
  variables:
    build_dir: ${RPN_CI_BASE_DIR}/${CI_PROJECT_PATH}/${CI_BUILD_REF_NAME}/${CI_PIPELINE_ID}/${REGULAR_MACHINE_1}
  script:
    - source ${RPN_CI_SCRIPTS}/io-server-setup-gnu-7.4.sh
    - cd ${build_dir}
    - make

test_job_regular_gnu_single_node:
  stage: test_batch
  variables:
    build_dir: ${RPN_CI_BASE_DIR}/${CI_PROJECT_PATH}/${CI_BUILD_REF_NAME}/${CI_PIPELINE_ID}/${REGULAR_MACHINE_1}
    NUM_CPUS: "40"
    OMPI_MCA_opal_cuda_support: "0"

    ORD_SOUMET_MACH: ${REGULAR_MACHINE_1}
    ORD_SOUMET_C: "${NUM_CPUS}"
    ORD_SOUMET_W: "30"
    ORD_SOUMET_JN: io-server-regular-single-node
    ORD_SOUMET_M: "4G"
    ORD_SOUMET_TMPFS: "1024M"
    MPI_COMMAND: "mpirun"

  script:
    - cd ${build_dir}
    - source ${RPN_CI_SCRIPTS}/io-server-setup-gnu-7.4.sh
    - source ${RPN_CI_SCRIPTS}/single_node_tests.sh

# test_job_regular_gnu_multi_node:
#   stage: test_batch
#   variables:
#     build_dir: ${RPN_CI_BASE_DIR}/${CI_PROJECT_PATH}/${CI_BUILD_REF_NAME}/${CI_PIPELINE_ID}/${REGULAR_MACHINE_1}
#     NUM_CPUS: "160"
#     OMPI_MCA_opal_cuda_support: "0"

#     ORD_SOUMET_MACH: ${REGULAR_MACHINE_1}
#     ORD_SOUMET_C: "${NUM_CPUS}x1"
#     ORD_SOUMET_W: "30"
#     ORD_SOUMET_JN: io-server-regular-multi-node
#     ORD_SOUMET_M: "4G"
#     ORD_SOUMET_TMPFS: "1024M"
#     MPI_COMMAND: "mpirun"

#   script:
#     - cd ${build_dir}
#     - source ${RPN_CI_SCRIPTS}/io-server-setup-gnu-7.4.sh
#     - source ${RPN_CI_SCRIPTS}/multi_node_tests.sh


configure_job_big_intel:
  stage: configure
  variables:
    build_dir: ${RPN_CI_BASE_DIR}/${CI_PROJECT_PATH}/${CI_BUILD_REF_NAME}/${CI_PIPELINE_ID}/big/intel
  tags:
    - login_node
  script:
    - . ssmuse-sh -d main/opt/cmake/cmake-3.16.4
    - mkdir -pv ${build_dir}
    - cd ${build_dir}
    - pwd
    - cmake ${CI_PROJECT_DIR}

build_job_big_intel:
  stage: build
  variables:
    build_dir: ${RPN_CI_BASE_DIR}/${CI_PROJECT_PATH}/${CI_BUILD_REF_NAME}/${CI_PIPELINE_ID}/big/intel
  tags:
    - login_node
  script:
    - . ssmuse-sh -d main/opt/cmake/cmake-3.16.4
    - cd ${build_dir}
    - pwd
    - make

test_job_big_intel_single_node:
  stage: test_batch
  variables:
    build_dir: ${RPN_CI_BASE_DIR}/${CI_PROJECT_PATH}/${CI_BUILD_REF_NAME}/${CI_PIPELINE_ID}/big/intel
    NUM_CPUS: "40"
    ORD_SOUMET_MACH: ${BIG_MACHINE_1}
    ORD_SOUMET_C: "${NUM_CPUS}"
    ORD_SOUMET_W: "30"
    ORD_SOUMET_JN: io-server-big-single-node
    MPI_COMMAND: "aprun"
  script:
    - cd ${build_dir}
    - pwd
    - source ${RPN_CI_SCRIPTS}/single_node_tests.sh

# test_job_big_intel_multi_node:
#   stage: test_batch
#   variables:
#     build_dir: ${RPN_CI_BASE_DIR}/${CI_PROJECT_PATH}/${CI_BUILD_REF_NAME}/${CI_PIPELINE_ID}/big/intel
#     NUM_CPUS: "160"
#     ORD_SOUMET_MACH: ${BIG_MACHINE_1}
#     ORD_SOUMET_C: "${NUM_CPUS}x1"
#     ORD_SOUMET_W: "30"
#     ORD_SOUMET_JN: io-server-big-multi-node
#     MPI_COMMAND: "aprun"
#   script:
#     - cd ${build_dir}
#     - source ${RPN_CI_SCRIPTS}/multi_node_tests.sh
