variables:
  build_dir: /home/vma000/ci-builds/io-server/${CI_PROJECT_PATH}/${CI_BUILD_REF_NAME}/${CI_PIPELINE_ID}
  install_dir: ${build_dir}/install
  GIT_SUBMODULE_STRATEGY: recursive
  ORD_SOUMET_SHELL: /bin/bash

before_script:
  - export ORDENV_SITE_PROFILE=20191220
  - export ORDENV_COMM_PROFILE=eccc/20200409
  - export ORDENV_GROUP_PROFILE=eccc/cmc/1.9.3
  - . /fs/ssm/main/env/ordenv-boot-20200204.sh

  - . ssmuse-sh -x main/opt/cmake/cmake-3.16.4

stages:
  - configure
  - build
  # - test
  # - install

configure_job:
  stage: configure
  script:
    - mkdir -pv ${build_dir}
    - cd ${build_dir}
    - cmake ${CI_PROJECT_DIR}

build_job:
  stage: build
  script:
    - cd ${build_dir}
    - make -j8

# test_job:
#   stage: test
#   script:
#     - cd ${build_dir}
#     - make test

