variables:
   GIT_SUBMODULE_STRATEGY: recursive
   ORD_SOUMET_SHELL: /bin/bash
   # Used to force HOST, remove once sici00 runners are restarted
   ECCI_BACKEND: banting
   ECCI_FRONTEND: ppp3
   BUILD_BASE_BASE_DIR: /home/sici000/special_builds
   BUILD_BASE_DIR: /home/sici000/special_builds/just_to_be_safe

before_script:
   - export CLICOLOR_FORCE=1

stages:
   - cleanup
   - build
   - test
   - package
#  - deploy

cleanup:all:
   stage: cleanup
   script:
      - rm -rfv ${BUILD_BASE_BASE_DIR}/just_to_be_safe

build:gnu-9.3.0:
   stage: build
#   only:
#      - master
#      - dev
#      - tags
   script:
      - source ci-env/latest/ubuntu-18.04-amd-64/gnu-9.3.0.sh
      - mkdir build_gnu-9.3.0
      - cd build_gnu-9.3.0
      - cmake ../ 
      - make
   artifacts:
      expire_in: 2 hrs
      paths:
         - build_gnu-9.3.0

test:gnu-9.3.0_job_regular_single_node:
   stage: test
   dependencies:
      - build:gnu-9.3.0
   variables:
      NUM_CPUS: "40"
      OMPI_MCA_opal_cuda_support: "0"

      ORD_SOUMET_MACH: ${ECCI_FRONTEND}
      ORD_SOUMET_C: "${NUM_CPUS}"
      ORD_SOUMET_W: "30"
      ORD_SOUMET_JN: io-server-regular-single-node
      ORD_SOUMET_M: "4G"
      ORD_SOUMET_TMPFS: "1024M"
      MPI_COMMAND: "mpirun"

   script:
      - source ci-env/latest/ubuntu-18.04-amd-64/gnu-9.3.0.sh
      - cd build_gnu-9.3.0
      - BUILD_PATH=`pwd`
      - source ../tests/script/single_node_tests.sh

# test:gnu-9.3.0_job_regular_multi_node:
#    stage: test
#    dependencies:
#       - build:gnu-9.3.0
#    variables:
#       NUM_CPUS: "160"
#       OMPI_MCA_opal_cuda_support: "0"

#       ORD_SOUMET_MACH: ${ECCI_FRONTEND}
#       ORD_SOUMET_C: "${NUM_CPUS}x1"
#       ORD_SOUMET_W: "30"
#       ORD_SOUMET_JN: io-server-regular-multi-node
#       ORD_SOUMET_M: "4G"
#       ORD_SOUMET_TMPFS: "1024M"
#       MPI_COMMAND: "mpirun"

#    script:
#       - source ci-env/latest/ubuntu-18.04-amd-64/gnu-9.3.0.sh
#       - cd build_gnu-9.3.0
#       - BUILD_PATH=`pwd`
#       - source ../tests/script/multi_node_tests.sh

build:XC50_intel-19.0.5:
   stage: build
   tags:
      - XC50-login
   variables:
      build_dir: ${BUILD_BASE_DIR}/${CI_PROJECT_PATH}/${CI_BUILD_REF_NAME}/${CI_PIPELINE_ID}/build_XC50_intel-19.0.5
#   only:
#      - master
#      - dev
#      - tags
   script:
      - set +e
      - source ci-env/latest/sles-15-skylake-64/intel-19.0.5.281.sh
      - SRC_DIR=$(pwd)
      - mkdir -pv ${build_dir}
      - cd ${build_dir}
      - pwd
      - cmake ${SRC_DIR}
      - make
   # artifacts:
   #    expire_in: 2 hrs
   #    paths:
   #       - build_XC50_intel-19.0.5

test:XC50_intel-19.0.5_job_single_node:
   stage: test
   dependencies:
      - build:XC50_intel-19.0.5
   # tags:
   #    - XC50-login
   variables:
      build_dir: ${BUILD_BASE_DIR}/${CI_PROJECT_PATH}/${CI_BUILD_REF_NAME}/${CI_PIPELINE_ID}/build_XC50_intel-19.0.5
      NUM_CPUS: "40"
      ORD_SOUMET_MACH: ${ECCI_BACKEND}
      ORD_SOUMET_C: "${NUM_CPUS}"
      ORD_SOUMET_W: "30"
      ORD_SOUMET_JN: xc50-intel-single-node
      MPI_COMMAND: "aprun"
   script:
      - set +e
      - source ci-env/latest/sles-15-skylake-64/intel-19.0.5.281.sh
      - SRC_DIR=$(pwd)
      - cd ${build_dir}
      - BUILD_PATH=`pwd`
      - source ${SRC_DIR}/tests/script/single_node_tests.sh

test:XC50_intel-19.0.5_job_multi_node:
   stage: test
   dependencies:
      - build:XC50_intel-19.0.5
   # tags:
   #    - XC50-login
   variables:
      build_dir: ${BUILD_BASE_DIR}/${CI_PROJECT_PATH}/${CI_BUILD_REF_NAME}/${CI_PIPELINE_ID}/build_XC50_intel-19.0.5
      NUM_CPUS: "160"
      NUM_SERVER_CPUS: "40"
      NUM_MODEL_CPUS: "120"
      ORD_SOUMET_MACH: ${ECCI_BACKEND}
      ORD_SOUMET_C: "${NUM_CPUS}x1"
      ORD_SOUMET_W: "30"
      ORD_SOUMET_JN: xc50-intel-multi-node
      MPI_COMMAND: "aprun"
   script:
      - set +e
      - source ci-env/latest/sles-15-skylake-64/intel-19.0.5.281.sh
      - SRC_DIR=$(pwd)
      - cd ${build_dir}
      - BUILD_PATH=`pwd`
      - source ${SRC_DIR}/tests/script/multi_node_tests.sh

package:XC50_intel-19.0.5:
   stage: package
   variables:
      build_dir: ${BUILD_BASE_DIR}/${CI_PROJECT_PATH}/${CI_BUILD_REF_NAME}/${CI_PIPELINE_ID}/build_XC50_intel-19.0.5
   only:
      - tags
   dependencies:
      - build:XC50_intel-19.0.5
   environment:
      name: testing
   script:
      - set +e
      - source ci-env/latest/sles-15-skylake-64/intel-19.0.5.281.sh
      - cd ${build_dir}
      - make package
      - ~/ci-admin-bundle/bin/ci-deploy-ssm.sh package

#package:intel-19.0.3:
#   stage: package
#   only:
#      - tags
#   dependencies:
#      - build:intel-19.0.3
#   environment:
#      name: testing
#   script:
#      - source ci-env/latest/ubuntu-18.04-skylake-64/intel-19.0.3.199.sh
#      - cd build_intel-19.0.3
#      - make package
#      - ~/ci-admin-bundle/bin/ci-deploy-ssm.sh package

package:gnu-9.3.0:
   stage: package
   only:
      - tags
   dependencies:
      - build:gnu-9.3.0
   environment:
      name: testing
   script:
      - source ci-env/latest/ubuntu-18.04-amd-64/gnu-9.3.0.sh
      - cd build_gnu-9.3.0
      - make package
      - ~/ci-admin-bundle/bin/ci-deploy-ssm.sh package
