variables:
   GIT_SUBMODULE_STRATEGY: recursive
   ORD_SOUMET_SHELL: /bin/bash
   BUILD_BASE_BASE_DIR: /home/sici000/special_builds/
   BUILD_BASE_DIR: /home/sici000/special_builds/just_to_be_safe
   RUN_BASE_BASE_DIR: /home/sici000/special_runs/
   RUN_BASE_DIR: /home/sici000/special_runs/just_to_be_safe

before_script:
   - export CLICOLOR_FORCE=1

stages:
   - cleanup
   - build
   - test
   - post-test-cleanup
   - package
#  - deploy

cleanup:u2:
   stage: cleanup
   tags:
      - U2
   script:
      - rm -rfv ${BUILD_BASE_BASE_DIR}/just_to_be_safe
      - rm -rfv ${RUN_BASE_BASE_DIR}/just_to_be_safe

post-test-cleanup:u2:
   stage: post-test-cleanup
   dependencies: 
      - test:U2_intel-2022.1.2_single_node
      - test:U2_intel-2022.1.2_multi_node
      - test:U2_intel-2022.1.2_many_nodes
      - test:U2_gnu-9.3.0_single_node
      - test:U2_gnu-9.3.0_multi_node
      - test:U2_aocc
      - test:U2_nvhpc
   tags:
      - U2
   script:
      - rm -rfv ${BUILD_BASE_BASE_DIR}/just_to_be_safe
      - rm -rfv ${RUN_BASE_BASE_DIR}/just_to_be_safe

####################
# U2 Intel 2022
build:U2_intel-2022.1.2:
   stage: build
   dependencies:
      - cleanup:u2
   tags:
      - U2
   variables:
      build_dir: ${BUILD_BASE_DIR}/${CI_PROJECT_PATH}/${CI_BUILD_REF_NAME}/${CI_PIPELINE_ID}/build_U2_intel-2022.1.2
      ORD_SOUMET_MACH: ${ECCI_FRONTEND}
      ORD_SOUMET_W: "20"
      ORD_SOUMET_C: "20"
      ORD_SOUMET_M: "2G"
   script:
      - set +e
      - source ~/ci-env/latest/rhel-8-icelake-64/inteloneapi-2022.1.2.sh
      - SRC_DIR=$(pwd)
      - mkdir -pv ${build_dir}
      - cd ${build_dir}
      - pwd
      - cmake ${SRC_DIR} -DIOSERVER_BUILD_PSEUDO_MODEL=ON -DIOSERVER_BUILD_TESTS=ON
      - make

test:U2_intel-2022.1.2_single_node:
   stage: test
   tags:
      - U2
   dependencies:
      - build:U2_intel-2022.1.2
   variables:
      build_dir: ${BUILD_BASE_DIR}/${CI_PROJECT_PATH}/${CI_BUILD_REF_NAME}/${CI_PIPELINE_ID}/build_U2_intel-2022.1.2
      run_dir: ${RUN_BASE_DIR}/${CI_PROJECT_PATH}/${CI_BUILD_REF_NAME}/${CI_PIPELINE_ID}/build_U2_intel-2022.1.2/single_node_test
      NUM_CPUS: "80"
      ORD_SOUMET_MACH: ${ECCI_FRONTEND}
      ORD_SOUMET_C: "${NUM_CPUS}"
      ORD_SOUMET_M: "2G"
      ORD_SOUMET_W: "60"
      ORD_SOUMET_JN: u2-intel-single-node
      MPI_COMMAND: "mpirun"
   script:
      - set +e
      - source ~/ci-env/latest/rhel-8-icelake-64/inteloneapi-2022.1.2.sh
      - SRC_DIR=$(pwd)
      - cd ${build_dir}
      - BUILD_PATH=`pwd`
      - mkdir -pv ${run_dir} && cd ${run_dir}
      - source ${SRC_DIR}/tests/script/single_node_tests.sh

test:U2_intel-2022.1.2_multi_node:
   stage: test
   tags:
      - U2
   dependencies:
      - build:U2_intel-2022.1.2
   variables:
      build_dir: ${BUILD_BASE_DIR}/${CI_PROJECT_PATH}/${CI_BUILD_REF_NAME}/${CI_PIPELINE_ID}/build_U2_intel-2022.1.2
      run_dir: ${RUN_BASE_DIR}/${CI_PROJECT_PATH}/${CI_BUILD_REF_NAME}/${CI_PIPELINE_ID}/build_U2_intel-2022.1.2/multi_node_test
      NUM_CPUS: "320"
      NUM_SERVER_CPUS: "80"
      NUM_MODEL_CPUS: "240"
      ORD_SOUMET_MACH: ${ECCI_FRONTEND}
      ORD_SOUMET_C: "${NUM_CPUS}x1"
      ORD_SOUMET_M: "2G"
      ORD_SOUMET_W: "60"
      ORD_SOUMET_JN: u2-intel-multi-node
      MPI_COMMAND: "mpirun"
   script:
      - set +e
      - source ~/ci-env/latest/rhel-8-icelake-64/inteloneapi-2022.1.2.sh
      - SRC_DIR=$(pwd)
      - cd ${build_dir}
      - BUILD_PATH=`pwd`
      - mkdir -pv ${run_dir} && cd ${run_dir}
      - source ${SRC_DIR}/tests/script/multi_node_tests.sh

test:U2_intel-2022.1.2_many_nodes:
   stage: test
   tags:
      - U2
   dependencies:
      - build:U2_intel-2022.1.2
   variables:
      build_dir: ${BUILD_BASE_DIR}/${CI_PROJECT_PATH}/${CI_BUILD_REF_NAME}/${CI_PIPELINE_ID}/build_U2_intel-2022.1.2
      run_dir: ${RUN_BASE_DIR}/${CI_PROJECT_PATH}/${CI_BUILD_REF_NAME}/${CI_PIPELINE_ID}/build_U2_intel-2022.1.2/many_nodes_test
      NUM_CPUS: "800"
      NUM_SERVER_CPUS: "80"
      NUM_MODEL_CPUS: "720"
      ORD_SOUMET_MACH: ${ECCI_FRONTEND}
      ORD_SOUMET_C: "${NUM_CPUS}x1"
      ORD_SOUMET_M: "2G"
      ORD_SOUMET_W: "60"
      ORD_SOUMET_JN: u2-intel-many-nodes
      MPI_COMMAND: "mpirun"
   script:
      - set +e
      - source ~/ci-env/latest/rhel-8-icelake-64/inteloneapi-2022.1.2.sh
      - SRC_DIR=$(pwd)
      - cd ${build_dir}
      - BUILD_PATH=`pwd`
      - mkdir -pv ${run_dir} && cd ${run_dir}
      - ${MPI_COMMAND} -n ${NUM_CPUS} ${BUILD_PATH}/tests/io_server_model_write  0 2 4 4 2 || exit -1
      - rm -fv pseudo_model_{1,2}

####################
# U2 GNU 9.3.0
build:U2_gnu-9.3.0:
   stage: build
   dependencies:
      - cleanup:u2
   tags:
      - U2
   variables:
      build_dir: ${BUILD_BASE_DIR}/${CI_PROJECT_PATH}/${CI_BUILD_REF_NAME}/${CI_PIPELINE_ID}/build_U2_gnu-9.3.0
      ORD_SOUMET_MACH: ${ECCI_FRONTEND}
      ORD_SOUMET_W: "20"
      ORD_SOUMET_C: "20"
      ORD_SOUMET_M: "2G"
   script:
      - set +e
      - source ~/ci-env/latest/rhel-8-amd-64/gnu-9.3.0.sh
      - SRC_DIR=$(pwd)
      - mkdir -pv ${build_dir}
      - cd ${build_dir}
      - pwd
      - cmake ${SRC_DIR} -DIOSERVER_BUILD_PSEUDO_MODEL=ON -DIOSERVER_BUILD_TESTS=ON
      - make

test:U2_gnu-9.3.0_single_node:
   stage: test
   tags:
      - U2
   dependencies:
      - build:U2_gnu-9.3.0
   variables:
      build_dir: ${BUILD_BASE_DIR}/${CI_PROJECT_PATH}/${CI_BUILD_REF_NAME}/${CI_PIPELINE_ID}/build_U2_gnu-9.3.0
      run_dir: ${RUN_BASE_DIR}/${CI_PROJECT_PATH}/${CI_BUILD_REF_NAME}/${CI_PIPELINE_ID}/build_U2_gnu-9.3.0/single_node_test
      NUM_CPUS: "80"
      ORD_SOUMET_MACH: ${ECCI_FRONTEND}
      ORD_SOUMET_C: "${NUM_CPUS}"
      ORD_SOUMET_M: "2G"
      ORD_SOUMET_W: "60"
      ORD_SOUMET_JN: u2-gnu-single-node
      MPI_COMMAND: "mpirun"
   script:
      - set +e
      - source ~/ci-env/latest/rhel-8-amd-64/gnu-9.3.0.sh
      - SRC_DIR=$(pwd)
      - cd ${build_dir}
      - BUILD_PATH=`pwd`
      - mkdir -pv ${run_dir} && cd ${run_dir}
      - source ${SRC_DIR}/tests/script/single_node_tests.sh

test:U2_gnu-9.3.0_multi_node:
   stage: test
   tags:
      - U2
   dependencies:
      - build:U2_gnu-9.3.0
   variables:
      build_dir: ${BUILD_BASE_DIR}/${CI_PROJECT_PATH}/${CI_BUILD_REF_NAME}/${CI_PIPELINE_ID}/build_U2_gnu-9.3.0
      run_dir: ${RUN_BASE_DIR}/${CI_PROJECT_PATH}/${CI_BUILD_REF_NAME}/${CI_PIPELINE_ID}/build_U2_gnu-9.3.0/multi_node_test
      NUM_CPUS: "320"
      NUM_SERVER_CPUS: "80"
      NUM_MODEL_CPUS: "240"
      ORD_SOUMET_MACH: ${ECCI_FRONTEND}
      ORD_SOUMET_C: "${NUM_CPUS}x1"
      ORD_SOUMET_M: "2G"
      ORD_SOUMET_W: "60"
      ORD_SOUMET_JN: u2-intel-multi-node
      MPI_COMMAND: "mpirun"
   script:
      - set +e
      - source ~/ci-env/latest/rhel-8-amd-64/gnu-9.3.0.sh
      - SRC_DIR=$(pwd)
      - cd ${build_dir}
      - BUILD_PATH=`pwd`
      - mkdir -pv ${run_dir} && cd ${run_dir}
      - source ${SRC_DIR}/tests/script/multi_node_tests.sh

################
# U2 AOCC
build:U2_aocc:
   stage: build
   dependencies:
      - cleanup:u2
   tags:
      - U2
   variables:
      build_dir: ${BUILD_BASE_DIR}/${CI_PROJECT_PATH}/${CI_BUILD_REF_NAME}/${CI_PIPELINE_ID}/build_U2_aocc
      ORD_SOUMET_MACH: ${ECCI_FRONTEND}
      ORD_SOUMET_W: "20"
      ORD_SOUMET_C: "20"
      ORD_SOUMET_M: "2G"
   script:
      - set +e
      - source ~/ci-env/latest/profile.sh
      - export MODULEPATH=${MODULEPATH}:/home/mfv001/modules
      - module load aocc
      - SRC_DIR=$(pwd)
      - mkdir -pv ${build_dir}
      - cd ${build_dir}
      - pwd
      - cmake ${SRC_DIR} -DUSE_ECCC_ENV_IF_AVAIL=0 -DCOMPILER_SUITE=aocc -DIOSERVER_BUILD_PSEUDO_MODEL=ON -DIOSERVER_BUILD_TESTS=ON
      - make

test:U2_aocc:
   stage: test
   tags:
      - U2
   dependencies:
      - build:U2_aocc
   variables:
      build_dir: ${BUILD_BASE_DIR}/${CI_PROJECT_PATH}/${CI_BUILD_REF_NAME}/${CI_PIPELINE_ID}/build_U2_aocc
      run_dir: ${RUN_BASE_DIR}/${CI_PROJECT_PATH}/${CI_BUILD_REF_NAME}/${CI_PIPELINE_ID}/build_U2_aocc/single_node_test
      NUM_CPUS: "80"
      ORD_SOUMET_MACH: ${ECCI_FRONTEND}
      ORD_SOUMET_C: "${NUM_CPUS}"
      ORD_SOUMET_M: "2G"
      ORD_SOUMET_W: "60"
      ORD_SOUMET_JN: u2-aocc-single-node
      MPI_COMMAND: "mpirun"
   script:
      - set +e
      - export MODULEPATH=${MODULEPATH}:/home/mfv001/modules
      - module load aocc
      - SRC_DIR=$(pwd)
      - cd ${build_dir}
      - BUILD_PATH=`pwd`
      - mkdir -pv ${run_dir} && cd ${run_dir}
      - source ${SRC_DIR}/tests/script/single_node_tests.sh

################
# U2 NVHPC
build:U2_nvhpc:
   stage: build
   dependencies:
      - cleanup:u2
   tags:
      - U2
   variables:
      build_dir: ${BUILD_BASE_DIR}/${CI_PROJECT_PATH}/${CI_BUILD_REF_NAME}/${CI_PIPELINE_ID}/build_U2_nvhpc
      ORD_SOUMET_MACH: ${ECCI_FRONTEND}
      ORD_SOUMET_W: "20"
      ORD_SOUMET_C: "20"
      ORD_SOUMET_M: "2G"
   script:
      - set +e
      - source ~/ci-env/latest/profile.sh
      - export MODULEPATH=${MODULEPATH}:/home/mfv001/modules
      - module load nvhpc
      - SRC_DIR=$(pwd)
      - mkdir -pv ${build_dir}
      - cd ${build_dir}
      - pwd
      - cmake ${SRC_DIR} -DUSE_ECCC_ENV_IF_AVAIL=0 -DCOMPILER_SUITE=nvhpc -DIOSERVER_BUILD_PSEUDO_MODEL=ON -DIOSERVER_BUILD_TESTS=ON
      - make

test:U2_nvhpc:
   stage: test
   tags:
      - U2
   dependencies:
      - build:U2_nvhpc
   variables:
      build_dir: ${BUILD_BASE_DIR}/${CI_PROJECT_PATH}/${CI_BUILD_REF_NAME}/${CI_PIPELINE_ID}/build_U2_nvhpc
      run_dir: ${RUN_BASE_DIR}/${CI_PROJECT_PATH}/${CI_BUILD_REF_NAME}/${CI_PIPELINE_ID}/build_U2_nvhpc/single_node_test
      NUM_CPUS: "80"
      ORD_SOUMET_MACH: ${ECCI_FRONTEND}
      ORD_SOUMET_C: "${NUM_CPUS}"
      ORD_SOUMET_M: "2G"
      ORD_SOUMET_W: "60"
      ORD_SOUMET_JN: u2-nvhpc-single-node
      MPI_COMMAND: "mpirun"
   script:
      - set +e
      - export MODULEPATH=${MODULEPATH}:/home/mfv001/modules
      - module load nvhpc
      - SRC_DIR=$(pwd)
      - cd ${build_dir}
      - BUILD_PATH=`pwd`
      - mkdir -pv ${run_dir} && cd ${run_dir}
      - source ${SRC_DIR}/tests/script/single_node_tests.sh

################
# Packaging
package:U2_intel-2022.1.2:
   stage: package
   variables:
      build_dir: ${BUILD_BASE_DIR}/${CI_PROJECT_PATH}/${CI_BUILD_REF_NAME}/${CI_PIPELINE_ID}/build_U2_intel-2022.1.2
   only:
      - tags
   dependencies:
      - build:U2_intel-2022.1.2
   environment:
      name: testing
   script:
      - set +e
      - source ~/ci-env/latest/rhel-8-icelake-64/intel-2022.1.2.sh
      - cd ${build_dir}
      - make package
      - ~/ci-admin-bundle/bin/ci-deploy-ssm.sh package

package:U2_gnu-9.3.0:
   stage: package
   variables:
      build_dir: ${BUILD_BASE_DIR}/${CI_PROJECT_PATH}/${CI_BUILD_REF_NAME}/${CI_PIPELINE_ID}/build_U2_gnu-9.3.0
   only:
      - tags
   dependencies:
      - build:U2_gnu-9.3.0
   environment:
      name: testing
   script:
      - set +e
      - source ~/ci-env/latest/rhel-8-amd-64/gnu-9.3.0.sh
      - cd ${build_dir}
      - make package
      - ~/ci-admin-bundle/bin/ci-deploy-ssm.sh package
